### ISSUE TITLE
Release installer.

### ISSUE THREAD

**Issue by Jakeverse** [Lixkote/10StartModenizer#2]
It will work on normal windows 11 22000.9? Explorer patcher and startallback dont support it but it has native windows 10 start menu. 

https://prnt.sc/4ATVBz6q3u1T

**Comment by Lixkote** [comment]
![image](https://github.com/Lixkote/10StartModenizer/assets/95425619/6fe64564-d644-4589-a80d-fc9b1a31b1e5)
Here is the screenshot of the Windows Mod i am talking about.

**Comment by Jakeverse** [comment]
Sad to hear but I'm happy that you replied. Thanks for sharing this, I will look for it. 😊
